<?php echo $this->docType() ?>
<html xml:lang="en" lang="en">
<head>
    <?php
    echo $this->headMeta() . PHP_EOL;
    echo $this->headTitle() . PHP_EOL;
    echo $this->headLink() . PHP_EOL;
    echo $this->headStyle() . PHP_EOL;
    echo $this->headScript() . PHP_EOL;
    ?>
</head>

<body>
<div id="master">
    <div id="container" class="rounded">
        <div id="header">
            <div id="topheader">
                <h1 id="logo"><a href="<?php echo $this->baseUrl('/') ?>" title="Demo Application"><strong>Demo</strong><i class="darkBlue">App</i></a></h1>
                <div id="topnav">
                    <?php //echo $this->accountSettings(); ?>
                </div>
            </div>
            <div id="midheader"></div>
            <div id="botheader"></div>
        </div>
        <div id="middle" class="">
            <div class="content">

                <?php echo $this->layout()->content; ?>

            </div>
        </div>
        <div id="footer"></div>
    </div>
</div>
<?php $this->inlineScript(); ?>
</body>
</html>